version: '3.9'
services:
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sqlserver
        environment:
            SA_PASSWORD: "Hai1234@"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - ./data:/var/opt/mssql/data
