version: '3.9'
services:
    database:
        container_name: db_for_learn
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - '${MYSQL_PORT}:${MYSQL_PORT}'
        volumes:
            - .:/opt/app/api
        command: ['--log_bin_trust_function_creators=1']